[package]
name = "abe-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-multi-proxy = { version = "0.1.2", features = ["mtls"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.98"
